/**
 * The source of the full editor's service worker, with the build's own file
 * list written in, so each build is a new worker that caches its own files.
 *
 * On install it caches the page and every file the build made, the language
 * catalogues and the export worker included, so the editor opens and works
 * with no network at all. A page load tries the network first and falls back
 * to the cached page; everything else comes from the cache when it is there.
 */
export function serviceWorkerSource(files: readonly string[], version: string): string {
  return `// Generated by the full editor's Vite build: do not edit by hand.
const CACHE = ${JSON.stringify(`trevixal-full-editor-${version}`)}
const FILES = ${JSON.stringify(['./', ...files.map((file) => `./${file}`)])}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(FILES))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      if (request.mode === 'navigate') {
        try {
          const response = await fetch(request)
          if (response.ok) await cache.put('./', response.clone())
          return response
        } catch {
          return (await cache.match('./')) ?? Response.error()
        }
      }
      const cached = await cache.match(request)
      if (cached) return cached
      const response = await fetch(request)
      if (response.ok) await cache.put(request, response.clone())
      return response
    }),
  )
})
`
}
