import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Trevixal',
  description: 'A WYSIWYG rich-text editor engine, written from scratch.',
  // Served from the root. VitePress uses `base` for its router as well as
  // for asset URLs, so a relative value breaks navigation rather than making
  // it portable. Set it to the subpath if you deploy under one.
  base: '/',
  srcExclude: ['**/README.md'],
  cleanUrls: true,
  lastUpdated: true,
  head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }]],

  themeConfig: {
    // The same glyph serves as the tab icon and the site mark.
    logo: '/favicon.svg',
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Using', link: '/using/' },
      { text: 'Extensions', link: '/extensions/' },
      // Eight top-level entries overflow the bar between 768 and 1050px wide,
      // where the theme still lays the menu out in full, so the less-visited
      // ones fold into two menus.
      {
        text: 'Reference',
        items: [
          { text: 'Reference', link: '/reference/core-api' },
          { text: 'Contributing', link: '/contributing/development' },
          // Generated by typedoc into `public/api`, so it is served as-is rather
          // than run through the markdown pipeline.
          { text: 'API', link: '/api/index.html', target: '_blank' },
        ],
      },
      {
        text: 'Try it',
        items: [
          { text: 'Full editor', link: '/full-editor' },
          { text: 'Playground', link: '/playground' },
        ],
      },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'The whole editor', link: '/guide/full-editor' },
          { text: 'React', link: '/guide/react' },
          { text: 'Vue', link: '/guide/vue' },
          { text: 'Svelte', link: '/guide/svelte' },
          { text: 'Angular', link: '/guide/angular' },
          { text: 'Web component', link: '/guide/web-component' },
          { text: 'No build step', link: '/guide/vanilla' },
          { text: 'Server rendering', link: '/guide/ssr' },
        ],
      },
      {
        text: 'Using the editor',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/using/' },
          { text: 'A tour of the editor', link: '/using/tour' },
          { text: 'Files', link: '/using/files' },
          { text: 'Appearance', link: '/using/appearance' },
          { text: 'Protecting a document', link: '/using/protection' },
          { text: 'Reviewing with tracked changes', link: '/using/review' },
          { text: 'Writing help', link: '/using/writing' },
          { text: 'Several documents', link: '/using/workspace' },
          { text: 'Keyboard and typing shortcuts', link: '/using/shortcuts' },
          { text: 'Every menu command', link: '/using/menus' },
        ],
      },
      {
        text: 'Extensions',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/extensions/' },
          { text: 'Tables', link: '/extensions/table' },
          { text: 'Images', link: '/extensions/image' },
          { text: 'Structural blocks', link: '/extensions/blocks' },
          { text: 'Media, attachments, link cards', link: '/extensions/embed' },
          { text: 'Equations', link: '/extensions/math' },
          { text: 'Diagrams', link: '/extensions/diagram' },
          { text: 'Word and RTF', link: '/extensions/export' },
          { text: 'Encryption and restrictions', link: '/extensions/security' },
          { text: 'Writing assistance', link: '/extensions/writing' },
          { text: 'Workspace', link: '/extensions/workspace' },
          { text: 'Track changes', link: '/extensions/track-changes' },
          { text: 'Syntax highlighting', link: '/extensions/code-highlight' },
          { text: 'Code formatting', link: '/extensions/format-code' },
          { text: 'Slash commands', link: '/extensions/slash-command' },
          { text: 'Emoji', link: '/extensions/emoji' },
        ],
      },
      {
        text: 'Concepts',
        items: [
          { text: 'State and the document', link: '/concepts/state' },
          { text: 'Schema', link: '/concepts/schema' },
          { text: 'Transactions and steps', link: '/concepts/transactions' },
          { text: 'Decorations', link: '/concepts/decorations' },
          { text: 'Extension points', link: '/concepts/extension-points' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'Core API', link: '/reference/core-api' },
          { text: 'The UI kit', link: '/reference/ui-kit' },
          { text: 'Styling and theming', link: '/reference/styling' },
          { text: 'What an export carries', link: '/reference/exports' },
          { text: 'Architecture', link: '/reference/architecture' },
          { text: 'Generated API reference', link: '/api/index.html', target: '_blank' },
        ],
      },
      {
        text: 'Extending',
        items: [
          { text: 'Write a callout extension', link: '/extending/callout' },
          { text: 'Adding things', link: '/extending/adding' },
        ],
      },
      {
        text: 'Contributing',
        items: [
          { text: 'Development', link: '/contributing/development' },
          { text: 'Testing', link: '/contributing/testing' },
          { text: 'Releasing', link: '/contributing/releasing' },
          { text: 'FAQ', link: '/contributing/faq' },
          { text: 'Glossary', link: '/contributing/glossary' },
        ],
      },
      {
        text: 'Decisions',
        items: [{ text: 'ADR index', link: '/adr/' }],
      },
    ],

    // The repository is private, so the icon led every reader to a 404.
    // Restore this line when it goes public.
    // socialLinks: [{ icon: 'github', link: 'https://github.com/adityabhalsod/trevixal-editor' }],

    search: { provider: 'local' },

    footer: {
      message: 'Apache-2.0',
      copyright: 'Trevixal: built from scratch, with no runtime dependencies.',
    },
  },
})
